name: Run Unit Test via Pytest  
  
on: [push]  
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: example
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Python
        run: uv python install
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Install curl
        run: apt update -qq; apt install -y curl
      - name: Install Atlas
        run: curl -sSf https://atlasgo.sh | sh
      - name: Run tests
        run: uv run pytest tests